### ISSUE TITLE
Unable to Add Issue 

### ISSUE THREAD

**Issue by slykhous** [rgoraya/wc_master#11]
The issue methane has a Wikipedia article, but it cannot be added.

**Comment by DinorahCr** [comment]
It also happens with "Chordata", it says the term "could not be found". (Submitted by panb)

**Comment by duyetln** [comment]
Fixed. The reason is not because the system can't find the article but because sometimes a Wikipedia article is formatted slightly different, which causes the parsing to fail. So 'Chordata' and 'Methane' can be added now.
