### ISSUE TITLE
Unable to access "My Issues"

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#13]
When one clicks "My Issues" to browse his/her issues, and error message is displayed: "We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly".

Replicate: 
1. Go to thiscausesthat.org
2. Play around with the website
3. Try to access your user account by clicking "My Issues"
4. Error message will appear

**Comment by duyetln** [comment]
It is fixed now. The user page will be accessible again in the next version.
