### ISSUE TITLE
Adding subset/superset 

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#14]
Every time you enter a super-set or subset, the website auto-directs you back to the page with causes and effects. This affects the user experience and interaction because It makes it tedious to continuously click back to the page when adding multiple subsets or super-sets. It can discourage people from adding content.

**Comment by DinorahCr** [comment]
It also happens when you reject/add suggestions

**Comment by rgoraya** [comment]
This should be addressed by the New layout. Keeping this open until the Correct partial reload problem is fixed (#35)

**Comment by rgoraya** [comment]
Closing this as #35 is now fixed!
