### ISSUE TITLE
Duplicated Suggestions

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#15]
Some suggestions of the same type are duplicated. For example, for issue "Global warming" (id is 4), "Developing country" (suggestion id 1833 and 1832) is being suggested twice as an type "R" suggestion. Both suggestions are already rejected by a user. Its unclear whether the duplication is an intended behaviour.

**Comment by duyetln** [comment]
It was a mistake. They are two completely different issues.
