### ISSUE TITLE
Issues cannot be listed as both caused and reduced by another issue 

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#18]
Issues cannot be linked as both caused and reduced by another issue. There are issues that in the long run and short run have different effects and need to be listed as such.

**Comment by duyetln** [comment]
This is a desired behavior. For now, an issue can be in only one type relationship with another issue. Whether this is correct or not from the environmental perspective, I don't know. The environmental team should discuss this matter with professor Tomlinson.
