### ISSUE TITLE
Website locks out user after deleting issue, doesn't log off

### ISSUE THREAD

**Issue by bravelittlescientist** [rgoraya/wc_master#2]
To replicate:
1. Delete an issue
2. Wait for "Delete" notification to clear
3. Navigate to homepage or other part of site
4. Locked out.

Discovered by Dinorah + Eugenia + Shibani

**Comment by bravelittlescientist** [comment]
Also, in at least one case the issue is not deleted after unlocking the site.

**Comment by duyetln** [comment]
Same reason with the 'deleting issue' problem.
