### ISSUE TITLE
Feature Request - Suggestions

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#21]
If there are multiple lines of suggestions and you reject or accept one of them, the system will bring you back to the top line of the suggestions. For a better user experience, it would be best if after accepting/rejecting the system did not alter your position. I found it tedious to have to continuously scroll down or up every time in order to go back to where I was.

**Comment by rgoraya** [comment]
Closing this as the new layout would handle suggestions differently.
