### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#24]
Birds cannot be added as a subset of animals. After multiple tries each time it says the URL is missing

**Comment by duyetln** [comment]
I'm not sure what causes this but Ant can be added now.

**Comment by duyetln** [comment]
Sometimes retrieving information from different pages can be unstable.

**Comment by rgoraya** [comment]
**The reason:** 
- When we add a new relationship, the system checks whether or not the new node exists as an Issue. 
- This check is currently performed based on a **string comparison** of the Wikipedia URLs of existing Issues and this new node.
- Now there was earlier a case when the title of the Newly created Issue was being picked from the query text field **(Not from the Media Wiki response itself as being done now)**.
- So in such cases, the system would think the added node does not already exist as an Issue and it tries to create a new Issue and therefore throws the error.

**Fix:**
- Perform **case-insensitive string comparisons** while determining whether the node exists as an issue or not.

**Comment by rgoraya** [comment]
Fixed!
