### ISSUE TITLE
Missing Picture 

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#25]
The issue wildfires picture has gone missing. When the issue was added, it had an appropriate picture. Now it has the gray folder indicating no picture. It has also been occurring with more issues as well.

**Comment by rgoraya** [comment]
Working on a similar piece #41. Assigning it to the lad named rgoraya!

**Comment by rgoraya** [comment]
Fixed this! Image options given on all forms (Add new Issue / Add new Relationship). Edit Image option done through Ajax in the Show page
