### ISSUE TITLE
Website locks out user after deleting relationship, doesn't log off

### ISSUE THREAD

**Issue by bravelittlescientist** [rgoraya/wc_master#3]
To replicate:
1. Delete a relationship (casual/inhibitory)
2. Wait for "Delete" notification to clear
3. Navigate to homepage or other part of site
4. Locked out.

Discovered by Dinorah + Eugenia + Shibani

**Comment by duyetln** [comment]
Because we're using the lock, it does not allow any deletions by default.  Once we remove the lock, the problem will go away. This behavior is expected.

**Comment by bravelittlescientist** [comment]
I think this needs to be reopened. It is a bug and a problem until the lock is removed, because it is unexpected behavior on the user side.

**Comment by duyetln** [comment]
Ok, I'll leave this one open so that everyone knows about it.

**Comment by rgoraya** [comment]
Fixed. Closing this.
