### ISSUE TITLE
Some bugs from recent deployment

### ISSUE THREAD

**Issue by duyetln** [rgoraya/wc_master#31]
1. Page 2 of user rgoraya's activity log fails to load (which causes an exception)
2. Reputation does not work when a user adds a separated new issue

**Comment by dLobatog** [comment]
1. No suggestions are pulled anymore

**Comment by rgoraya** [comment]
Daniel, the recent deployment did not require any changes (other than the js respond_to's for the AJAX calls) in the issue 'create' action. So if something went down it was probably while doing the merge. It should just be a matter of comparing the code on the repo with your local code (where the suggestions are being retrieved successfully)

**Comment by rgoraya** [comment]
Assigning to @nguyendl

**Comment by duyetln** [comment]
Bug # 2 is fixed. I'm working on # 1 (the user page's problem).

**Comment by duyetln** [comment]
Fixed. Just adjusted a few lines of code.
