### ISSUE TITLE
Relationship is not being added

### ISSUE THREAD

**Issue by duyetln** [rgoraya/wc_master#32]
"Precipitation (meteorology)"  can't be added under "Climate Change" reduces

**Comment by rgoraya** [comment]
Duyet, What exact error are you getting?
Or does this happen because Media wiki data is not fetched for this?

**Comment by duyetln** [comment]
I don't know how the error occurred. This is a bug report submitted by a user.

**Comment by rgoraya** [comment]
I think it should be fixed with my code change yesterday.

**Comment by rgoraya** [comment]
Duplicate reported by Rene Slykhous: 
_Trying to create the issue uplift (geology), I found the search ended without any results or error message. See below._

**Comment by rgoraya** [comment]
possible duplicate of #33?

**Comment by duyetln** [comment]
They are the same issue. I'm closing this.

**Comment by rgoraya** [comment]
agree.
