### ISSUE TITLE
"Suggestions" label in causes/inhibitors is confusing

### ISSUE THREAD

**Issue by bravelittlescientist** [rgoraya/wc_master#4]
"Suggestion" implies that a user would be submitting / commenting on website - like it should be an input box. Because what we're inputting is suggestions, it's unclear whether it's computer generated or user generated. Some issues have lots of suggestions, other issues have none, which is also confusing. Why would a user add a suggestion if they could add a link instead?

Suggestions by system should have different look/feel than suggestions by users.

Other possible labels: System suggestions, or a mouseover with text like "Suggestion by computer"

Reported by Shibani + Dinorah

**Comment by dLobatog** [comment]
I would say that a good way to tackle this problem would be to rename "Suggestions" by "Computer-generated suggestions" to improve clarity. 
Users cannot add suggestions as of now, they just can add "user accepted" causes/effects, or accept/reject a suggestion, am I right?

**Comment by rgoraya** [comment]
I feel this has been addressed in the new layout. Closing the issue for now. Reopen if you feel it persists.
