### ISSUE TITLE
Wrong picture

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#41]
**As reported by Rene Slykhous:**
- _Incorrect picture on stress (mechanics). It is a picture of a stressed out person. The summary for the article is for stress disambiguated. However when you click on see more on Wikipedia, it takes you to the correct page_
- _Wrong Image for an issue. “Animal” and a few other issues have an incorrect image. See below, the image for animal is Animal from the Muppets_

As reported by Joel Ross:
- _Also "Shearing (physics)", which has unintentionally hilarious meaning given its relationship to stress (see http://thiscausesthat.org/issues/2367-shearing-physics?rel_type=is+a+subset+of&rel_id=3305)_

**Comment by joelwross** [comment]
Also "Shearing (physics)", which has unintentionally hilarious meaning given its relationship to stress (see http://thiscausesthat.org/issues/2367-shearing-physics?rel_type=is+a+subset+of&rel_id=3305)

**Comment by rgoraya** [comment]
Not a bug really :)
We are relying upon Google to get us the best image (who does it better than Google?) if we do not get a relevant image from Wikipedia itself. A possible workaround is to offer options (say 3 top google image results) to choose from.

**Comment by rgoraya** [comment]
Introduced the new functionality in the Add New Relationship. Will close this once integrated in Add New Issue page as well. Bringing it down to Low priority.

**Comment by rgoraya** [comment]
Fixed this! Image options given on all forms (Add new Issue / Add new Relationship). Edit Image option done through Ajax in the Show page
