### ISSUE TITLE
403 forbidden: Suggestions

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#42]
- There are times when we encounter **403 forbidden: Permission Error** when accessing Wikipedia page and parsing it to generate suggestions (when adding a new relationship).
- It is a known issue but we do need to address this issue soon as this may affect the system in the long term.
- Also, even if we encounter this problem, can we go ahead and set up the relationship anyway and try to generate suggestions in the background? 
- Perhaps before loading a show page we can check whether the current issue has suggestions. And if not then it can retry.

**Comment by dLobatog** [comment]
Question, where is the first place where we find the 403? The javascript retrieving the info from MediaWiki API , the suggestions model or what?

**Comment by rgoraya** [comment]
This happens in the Suggestions Model Where we use HPRICOT gem to parse the page after buffering it using OpenURI.

On javaScript side it never faces this error because in that case the data comes not by reading in the entire page but by accessing it from MediWiki API. Could we use the same approach on Suggestion model to counter this? That is, instead of using hpricot gem, we find a way to access media wiki API from the model itself.

I would start by looking into some rails mediawiki gems. A quick search led me to this:
http://notgeeklycorrect.com/geek-stuff/2008/08/05/how-to-search-on-a-mediawiki-wikipedia-with-ruby-on-rails

**Comment by duyetln** [comment]
Daniel, if you need to trace where the 403 starts, look in the error report sent to the bug report email.

Apparently, the error starts at the suggestion model:

 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:277:in `open_http'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:616:in`buffer_open'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:162:in`catch'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:132:in`open_uri'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:518:in `open'
 /opt/ruby-enterprise/lib/ruby/1.8/open-uri.rb:30:in`open'
 app/models/suggestion.rb:38:in `get_suggestions'     <----------------------------------- here
 app/controllers/issues_controller.rb:252:in`initialize_suggestion_object'
 app/controllers/issues_controller.rb:233:in `add_new_issue'
 app/controllers/issues_controller.rb:186:in`create'
 actionpack (3.0.7) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
 actionpack (3.0.7) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
 actionpack (3.0.7) lib/abstract_controller/base.rb:150:in `process_action'
 actionpack (3.0.7) lib/action_controller/metal/rendering.rb:11:in`process_action'
 actionpack (3.0.7) lib/abstract_controller/callbacks.rb:18:in `process_action'
 activesupport (3.0.7) lib/active_support/callbacks.rb:456:in`_run__320258323__process_action__1623385099__callbacks'
 activesupport (3.0.7) lib/active_support/callbacks.rb:410:in `send'
 activesupport (3.0.7) lib/active_support/callbacks.rb:410:in`_run_process_action_callbacks'
 activesupport (3.0.7) lib/active_support/callbacks.rb:94:in `send'
 activesupport (3.0.7) lib/active_support/callbacks.rb:94:in`run_callbacks'
 actionpack (3.0.7) lib/abstract_controller/callbacks.rb:17:in `process_action'
 actionpack (3.0.7) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
 activesupport (3.0.7) lib/active_support/notifications.rb:52:in `instrument'
 activesupport (3.0.7) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
 activesupport (3.0.7) lib/active_support/notifications.rb:52:in `instrument'
 actionpack (3.0.7) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
 actionpack (3.0.7) lib/action_controller/metal/rescue.rb:17:in `process_action'
 actionpack (3.0.7) lib/abstract_controller/base.rb:119:in`process'
 actionpack (3.0.7) lib/abstract_controller/rendering.rb:41:in `process'
 actionpack (3.0.7) lib/action_controller/metal.rb:138:in`dispatch'
 actionpack (3.0.7) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
 actionpack (3.0.7) lib/action_controller/metal.rb:178:in`action'
 actionpack (3.0.7) lib/action_dispatch/routing/route_set.rb:62:in `call'
 actionpack (3.0.7) lib/action_dispatch/routing/route_set.rb:62:in`dispatch'
 actionpack (3.0.7) lib/action_dispatch/routing/route_set.rb:27:in `call'
 rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in`call'
 rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in `recognize'
 rack-mount (0.6.14) lib/rack/mount/code_generation.rb:82:in`optimized_each'
 rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in `recognize'
 rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in`call'
 actionpack (3.0.7) lib/action_dispatch/routing/route_set.rb:493:in `call'
 exception_notification (2.5.2) lib/exception_notifier.rb:25:in`call'
 actionpack (3.0.7) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
 actionpack (3.0.7) lib/action_dispatch/middleware/head.rb:14:in`call'
 rack (1.3.1) lib/rack/methodoverride.rb:24:in `call'
 actionpack (3.0.7) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
 actionpack (3.0.7) lib/action_dispatch/middleware/flash.rb:182:in `call'
 actionpack (3.0.7) lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
 actionpack (3.0.7) lib/action_dispatch/middleware/cookies.rb:302:in `call'
 activerecord (3.0.7) lib/active_record/query_cache.rb:32:in`call'
 activerecord (3.0.7) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
 activerecord (3.0.7) lib/active_record/query_cache.rb:12:in`cache'
 activerecord (3.0.7) lib/active_record/query_cache.rb:31:in `call'
 activerecord (3.0.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in`call'
 actionpack (3.0.7) lib/action_dispatch/middleware/callbacks.rb:46:in `call'
 activesupport (3.0.7) lib/active_support/callbacks.rb:416:in`_run_call_callbacks'
 actionpack (3.0.7) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
 rack (1.3.1) lib/rack/sendfile.rb:101:in`call'
 actionpack (3.0.7) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
 actionpack (3.0.7) lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
 railties (3.0.7) lib/rails/rack/logger.rb:13:in `call'
 rack (1.3.1) lib/rack/runtime.rb:17:in`call'
 rack (1.3.1) lib/rack/lock.rb:15:in `call'
 railties (3.0.7) lib/rails/application.rb:168:in`call'
 railties (3.0.7) lib/rails/application.rb:77:in `send'
 railties (3.0.7) lib/rails/application.rb:77:in`method_missing'
 passenger (2.2.8) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
 passenger (2.2.8) lib/phusion_passenger/abstract_request_handler.rb:207:in`main_loop'
 passenger (2.2.8) lib/phusion_passenger/rack/application_spawner.rb:114:in `run'
 passenger (2.2.8) lib/phusion_passenger/rack/application_spawner.rb:65:in`spawn_application'
 passenger (2.2.8) lib/phusion_passenger/utils.rb:184:in `safe_fork'
 passenger (2.2.8) lib/phusion_passenger/rack/application_spawner.rb:58:in`spawn_application'
 passenger (2.2.8) lib/phusion_passenger/rack/application_spawner.rb:41:in `spawn_application'
 passenger (2.2.8) lib/phusion_passenger/spawn_manager.rb:159:in`spawn_application'
 passenger (2.2.8) lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
 passenger (2.2.8) lib/phusion_passenger/abstract_server.rb:352:in`__send__'
 passenger (2.2.8) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
 passenger (2.2.8) lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
 passenger (2.2.8) bin/passenger-spawn-server:61

**Comment by rgoraya** [comment]
403 Forbidden Corrected in the suggestion Model.
