### ISSUE TITLE
Keyboard interactions with quicksearch

### ISSUE THREAD

**Issue by joelwross** [rgoraya/wc_master#43]
I keep wanting the quicksearch at the top of the site to respond to the keyboard. So that when I type in "deforest" and "deforestation" is first on the list, I can use the arrow keys to move down to it and hit "enter" to select it. See interaction on Google et al.

**Comment by rgoraya** [comment]
This has been implemented for addnew http://www.thiscausesthat.org/issues/new
Will get this done for site-wide search too. Thanks for noticing!

**Comment by duyetln** [comment]
Let me work on this feature. Is it ok?

**Comment by rgoraya** [comment]
Sure!

**Comment by duyetln** [comment]
I have added this functionality to the global issue search box and also disallowed searches with weird values like " " or " d" (which now reduces to empty string and "d" respectively).
