### ISSUE TITLE
Suggestions Don't Display

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#48]
- With the New layout the suggestions do not display. 
- This is not a bug but it was kept pending in order to ensure the new layout reaches a more stable state. 
- Logging this as an issue now.

**Comment by dLobatog** [comment]
I'm working on this now

**Comment by rgoraya** [comment]
Are you working on Displaying the suggestions on issue/show page or are you working on generating them in the controller.

**Comment by dLobatog** [comment]
I'm working on displaying them, they are generated correctly so far, I will make some adjustments to the way they are generated later on.

**Comment by dLobatog** [comment]
Ok done :) They show up. I have a couple of questions. Since the issue thumbnails are shown according to the issue 'short_url', and suggestions do not have a short_url, I do not have any picture to show for them, what should I show, a question mark maybe?

Then again, what is the interaction supposed to be when the user clicks on a suggestion that has not been accepted yet?
Should it link to the wikipedia article maybe?

**Comment by rgoraya** [comment]
Good job! I'll soon check them out.

Yes displaying the question mark would be the right way. ( there's one in our images folder that'll do the job)

And the interaction on clicking one of these would be to make the media wiki call (the one we make when we add a new relationship to display the corresponding wikipedia data) and populate the lower half of the page with the data received. I can work on this bit once the top bar starts displaying them correctly.

**Comment by rgoraya** [comment]
Did you check this in? Please let me know so that I can start working on the mediawiki part.

**Comment by rgoraya** [comment]
Okay, well I cloned your branch and tested this. Somehow, I could not see the suggestions in my quick user testing. Am I missing something here?

**Comment by dLobatog** [comment]
Oh no no I haven't checked this in yet because I am still finishing it, don't use it yet!

**Comment by dLobatog** [comment]
Well now they are displayed. I will be working on this this week.

Yet to do: Include accept/reject button, pull information on click

**Comment by rgoraya** [comment]
- Thanks for working on this Daniel. 
- I am already working on getting the media wiki information retrieval on the show page (on clicking suggestions). Could you please work on the 403 forbidden we encounter sometimes when we try to generate suggestions?
- I was wondering if we could move the suggestion generation to "Show" action and just check :if there are no suggestions, try to retrieve, and if 403 is encountered, then try the next time show page is opened. 
- I am happy to talk more about this if its not clear. I will modify the issue #42 with more details soon.

**Comment by rgoraya** [comment]
Suggestions acceptance/rejection/duplication removal is now fully functional
