### ISSUE TITLE
User Acitivities page: Nil Object Error

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#49]
We are using unobtrusive AJAX calls for deletion of:
- issues
- relationships
- comments
- references

The User page encounters the above error after doing a deletion.

**Comment by rgoraya** [comment]
I just noticed that the _Reputation::Utils.reputation_ call in the _destroy_ method within the _comments_ and _references_ controller has _:action=>:create_.
Is there a reason why this is so? I was wondering if that needs to be corrected to _:action=>:destroy_.
For now, I have removed paper trail from the _comment_ model and controller as we are not tracking comments when generating _activities_  in the user model.

Keeping this open until we:
- Correct the action in the _Reputation::Utils.reputation_ calls
- Handle the version.item_type "comment" in the _user.rb_

**Comment by duyetln** [comment]
I have no idea who put reputation call in comments controller. We don't need it there. About the reference controller, the action should be :action=>:destroy. Probably a typo.

**Comment by duyetln** [comment]
We still need paper_trail in the comment model because when a relationship is deleted, we would want to keep a "copy" of those comments so that when the same relationship is reverted back to life, those comments will be reverted as well. If we don't use paper trail, all comments will be lost upon relationship deletion.

**Comment by duyetln** [comment]
Fixed. I added some lines of code to handle Comment-typed versions.

Also, the activity page will show comment activities.

**Comment by rgoraya** [comment]
Please check this in if you haven't already. Thanks!

On Tue, Feb 21, 2012 at 1:12 PM, nguyendl <
reply@reply.github.com

> wrote:
> 
> Fixed. I added some lines of code to handle Comment-typed versions.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rgoraya/wc_master/issues/49#issuecomment-4088922

## 

Sincere Thanks!

Goraya Raminder Singh
Bren School of Information and Computer Sciences
University of California, Irvine
Irvine, CA 92697-3425rgoraya@uci.edu
