### ISSUE TITLE
Can't enter a space in the global search bar

### ISSUE THREAD

**Issue by joelwross** [rgoraya/wc_master#53]
When I try to search for "climate change", the space is removed immediately after I add it so I instead search for "climatechange". Note that I can still add spaces on their own if there is no other content.

**Comment by duyetln** [comment]
Just an unintended side effect of disallowing keywords that start or end with spaces. Fixed.

**Comment by rgoraya** [comment]
Reopening as it still exists on the live version.

**Comment by rgoraya** [comment]
Fixed!
