### ISSUE TITLE
Linking a non-existing effect to an issue

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#6]
When you trying to link an effect that has not been created  to an issue the system will just appear to be loading but will not create the link nor notify you that it cannot be done. It would be useful if it will display an error message saying something along the lines of ”The effect you are trying to link does not exist” and then provide you with the option to create it at the moment.

To Replicate:
1. Go to an existing issue
2. Try to link a effect that is not in database to said issue 3. It would appear to be loading but never gets to create it

**Comment by duyetln** [comment]
Could you elaborate more on this problem? This seems to be a really strange bug to me. The system should be able to create a new effect anytime that effect is not already in the system.
I did try to replicate the problem and I found that once in a while the loading time is a bit slow (but in the end the effect _is_ created). Perhaps this confuses the user into thinking the system fails?

**Comment by DinorahCr** [comment]
I concur, it seems to work fine. I assume this is because by the time I reported this issue the system did not allow you to link issues that had not been previously created. Now, the system can create a non-existent issue while linking making this bug obsolete.

**Comment by DinorahCr** [comment]
The systems creates the issue and adds it to the database. Fixed!
