### ISSUE TITLE
Modify: 500, 404, 422 HTMLs

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#61]

**Comment by dLobatog** [comment]
I take this

**Comment by dLobatog** [comment]
I close this as this is already done (it's in my repository so far)

**Comment by dLobatog** [comment]
I see you want to keep issues open until they live version has them solved. Reopen then until next deploy.

**Comment by rgoraya** [comment]
Good work Daniel. This is online now. Closing this.
