### ISSUE TITLE
Repeated References

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#7]
Within an issue, if an user adds a reference to a causality/issue and someone had already added that reference, even if its linked to another causality, the system would show the link twice. The system should be able to recognize if two references are the same and only show it once.

To Replicate:
1. Go to an existing issue
2. Check under ”References” and add one of the references to another casualty than the one that is already linked to
3. The link will appear twice, instead of just one time

**Comment by rgoraya** [comment]
With the New layout, the user can at a time only see the references for a particular relationship that was selected (clicked on). In other words, the displayed references at a particular time _belong to_ the relationship. 
Closing this Issue. Reopen if you feel otherwise.
