### ISSUE TITLE
Improve Wait feedback - (replace spinners with messages)

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#74]

**Comment by dLobatog** [comment]
Remember what we wanted to accomplish on first 'show' of an issue with no suggestions, that is, bringing the layout first and retrieving the suggestions in the background. HTTP streaming makes it possible but not with HAML, only ERB or HTML. Should we leave this as is for now?

https://github.com/nex3/haml/issues/436

**Comment by rgoraya** [comment]
Hmm, this looks very interesting. 
I guess we can leave it as is right now. I have another solution in mind. Will create a separate issue discussing that.

**Comment by rgoraya** [comment]
Fixed this for the Show page.
