### ISSUE TITLE
Poorly disambiguated issues from Wikipedia are parsed incorrectly

### ISSUE THREAD

**Issue by bravelittlescientist** [rgoraya/wc_master#8]
Some issues with identical names on Wikipedia have no disambiguation indication, and our system does not allow us to choose the meaning.

To replicate:
1. Click "Add new issue"
2. Type "Insecticide"
3. Click "Preview"
4. Nirvana album appears

**Comment by duyetln** [comment]
Did you mean 'insecticide' or incesticide? There's an entry created on the system with the name 'incesticide'. Probably you mixed up the two.

**Comment by bravelittlescientist** [comment]
I think you're right :).

**Comment by duyetln** [comment]
Typo. It happens to everyone :)
